### ISSUE TITLE
Event parser should fail on oversized fields

### ISSUE THREAD

**Issue by istreeter** [snowplow/snowplow-scala-analytics-sdk#115]
Events emitted by enrich should conform to [the atomic event schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0).  We plan to change Enrich so that it [enforces the constraints on field maximum string length](https://github.com/snowplow/enrich/issues/517).

The Event parser can therefore become more strict.  Any event that violates the maximum string length should be rejected.  This will help loaders, because it guarantees that anything that is successfully parsed can be loaded to the warehouse.

**Comment by paulboocock** [comment]
What defines the maximum size of a field? My instinct is that this feels strange to fail in the Analytics SDKs if they can happily handy the parsing of any size field?

**Comment by istreeter** [comment]
@paulboocock [the Iglu schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0) defines the maximum size.  It's true that the analytics sdk currently handles parsing any size field, but it comes with the disadvantage that consumers of the Event (e.g. loaders) have no guarantees that the event conforms to the schema.  By adding validation here, we can promise to consumers that the returned value is not just a `com.snowplowanalytics.snowplow.analytics.scalasdk.Event`, but it is also a **Snowplow™** event.

**Comment by paulboocock** [comment]
That makes sense, particularly with it needing to match the Iglu schema for an atomic event. Would perhaps be nice to consider validation of the event as an option rather than the only way? Whilst events might be "incorrect" if they are too big, they are only really too big for loaders. If you were using a Snowplow pipeline off the streams only then you might not be quite as bothered that events conform the the Atomic event schema (even if thats probably a bad life choice).

I think validating the event could (should!) be the new default, but there's an option to parse with no validation. This might also make this libary bump to v3 too.
