### ISSUE TITLE
Add Scala 2.12 support

### ISSUE THREAD

**Issue by benhutchison** [snowplow/snowplow-scala-analytics-sdk#41]
2.12 was released November  2016 and is now the current official Scala release. Many libraries are shifting their default binary compatibility to 2.12.

**Comment by chuwy** [comment]
Fully agree!

Main reason we stuck on 2.11 is that we rely on Json4s 3.2 and cannot bump it because newer versions are binary incompatible with Spark, which is main environment for Analytics SDK.

But good news is that recently Json4s 3.2.11 was [backported](https://github.com/json4s/json4s/commit/8c2865089604677578e3d858056014b12d2a78dc) to Scala 2.12, which means nothing holds us anymore on 2.11. 

Thanks for raising!
